name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          client/package-lock.json
          server/package-lock.json
          
    - name: Install client dependencies
      run: |
        cd client
        npm ci
        
    - name: Build client
      run: |
        cd client
        npm run build
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build backend
      run: |
        cd Messenger
        dotnet restore
        dotnet build --configuration Release
        
    # - name: Build voice server
    #   run: |
    #     cd server
    #     npm ci --only=production
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 2.59.41.26
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home
          
          # Останавливаем контейнеры в deploy папке
          echo "Stopping containers..."
          if [ -d "Whithin-deploy" ]; then
            cd Whithin-deploy
            docker-compose down || true
            cd ..
          fi
          
          # Создаем бэкап deploy папки
          echo "Creating backup..."
          if [ -d "Whithin-deploy" ]; then
            rm -rf Whithin-deploy-backup.old
            mv Whithin-deploy-backup Whithin-deploy-backup.old 2>/dev/null || true
            cp -r Whithin-deploy Whithin-deploy-backup || true
          fi
          
          # Очищаем старые образы
          echo "Cleaning old images..."
          docker system prune -f
          
    - name: Upload files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 2.59.41.26
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/home/Whithin-deploy"
        strip_components: 1
        
    - name: Start services
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 2.59.41.26
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        timeout: 30m
        script: |
          cd /home/Whithin-deploy
          
          # Устанавливаем права
          echo "Setting permissions..."
          chmod +x docker-compose.yml
          chmod -R 755 /home/Whithin-deploy
          
          # Запускаем Docker контейнеры (dev версия)
          echo "Starting services..."
          docker-compose up -d --build
          
          # Ждем запуска сервисов
          echo "Waiting for services to start..."
          sleep 30
          
          # Health check
          echo "Health check..."
          if curl -f http://localhost/api/health || curl -f https://whithin.ru/api/health; then
            echo "Deployment successful!"
          else
            echo "Health check failed!"
            # Rollback
            echo "Rolling back..."
            docker-compose down
            if [ -d "../Whithin-deploy-backup.old" ]; then
              rm -rf ../Whithin-deploy-backup
              mv ../Whithin-deploy-backup.old ../Whithin-deploy-backup
            fi
            exit 1
          fi
          
          # Показываем статус контейнеров
          echo "Container status:"
          docker-compose ps
